name: Generate changelog
description: Generate changelog for new version of Swift library
inputs:
  version:
    description: New version to release
    required: false
outputs:
  changelog:
    description: The generated changelog for the new version
    value: ${{ steps.conventional_changelog.outputs.changelog }}
  clean_changelog:
    description: The generated changelog for the new version without the version name in it
    value: ${{ steps.conventional_changelog.outputs.clean_changelog }}
  version:
    description: The new version
    value: ${{ steps.conventional_changelog.outputs.version }}
  tag:
    description: The name of the generated tag
    value: ${{ steps.conventional_changelog.outputs.tag }}
  skipped:
    description: boolean to check if this step have been skipped
    value: ${{ steps.conventional_changelog.outputs.skipped }}

runs:
  using: composite
  steps:
    - name: Conventional Changelog Action
      id: conventional_changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ github.token }}
        git-message: 'chore(CHANGELOG): update for {version}'
        git-user-name: ${{ github.actor }}
        git-user-email: soumya.mahunt@gmail.com
        release-count: 0
        version-file: './package.json'
        version-path: version
        fallback-version: '1.0.0'
        config-file-path: ${{ github.action_path }}/config.js
        pre-commit: ${{ github.action_path }}/pre_commit_hook.js
        pre-changelog-generation: ${{ github.action_path }}/pre_changelog_hook.js
      env:
        VERSION: ${{ inputs.version }}
        NODE_PATH: ${{ github.workspace }}/node_modules
