name: Setup action for Swift library
description: Setup action for Swift library
inputs:
  swift:
    description: Swift version to use
    required: false
    default: latest
runs:
  using: composite
  steps:
    - name: Setup Cocoapods
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: latest

    - name: Setup swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ inputs.swift }}

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '17'

    - name: Setup npm pacakges
      if:  steps.check_version_bump.outputs.release_type == ''
      run: npm install
      shell: bash
