name: Setup action for Swift library
description: Setup action for Swift library
inputs:
  swift:
    description: Swift version to use
    required: false
    default: '5.7'
  xcode:
    description: Xcode version to use
    required: false
    default: latest-stable
runs:
  using: composite
  steps:
    - name: Setup Xcode version
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1.4.1
      with:
        xcode-version: ${{ inputs.xcode }}

    - name: Setup Cocoapods
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: latest

    - name: Setup swift
      if: runner.os != 'macOS'
      uses: swift-actions/setup-swift@v1.20.0
      with:
        swift-version: ${{ inputs.swift }}

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '17'

    - name: Setup npm pacakges
      if:  steps.check_version_bump.outputs.release_type == ''
      run: npm install
      shell: bash
