name: Analyze

on:
  workflow_call:
    inputs:
      matrix:
        description: |
          The strategy-matrix to use containing runner OS and languages for CodeQL analysis
          along with optional Swift and Xcode versions
        required: true
        type: string
      tracked-files:
        description: The files on which changes tracked and based on change actions are run
        required: false
        type: string
        default: |
          Sources/**/*.swift
          Tests/**/*
          Package*.swift

concurrency:
  group: scan-${{ github.ref }}
  cancel-in-progress: true

env:
  CODEQL_ENABLE_EXPERIMENTAL_FEATURES_SWIFT: true

jobs:
  codeql:
    name: CodeQL Analysis on ${{ matrix.os }} for language ${{ matrix.language }}
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}

    steps:
    - name: Check should proceed running steps
      id: precondition
      uses: SwiftyLab/ci/actions/condition@main
      with:
        files: ${{ inputs.tracked-files }}

    - name: Setup repository
      if: steps.precondition.outputs.proceed == 'true'
      uses: SwiftyLab/ci/actions/setup@main
      with:
        swift: ${{ matrix.swift }}
        xcode: ${{ matrix.xcode }}

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Build package products
      run: |
        npm run build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
