name: Check if release needed

on:
  workflow_call:
    inputs:
      os:
        description: OS to build products on
        required: false
        type: string
        default: macos-latest
      swift:
        description: Swift version to use
        required: false
        type: string
        default: latest
      version:
        description: New version to release
        required: false
        type: string
    secrets:
      COCOAPODS_TRUNK_TOKEN:
        description: CocoaPods Trunk Token to publish release
        required: true

jobs:
  changelog:
    name: Generate release changelogs
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      version: ${{ steps.changelog.outputs.version }}
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup repository
      uses: SwiftyLab/ci/actions/setup@main
      with:
        swift: ${{ inputs.swift }}

    - name: Conventional Changelog Action
      id: changelog
      uses: SwiftyLab/ci/actions/changelog@main
      with:
        version: ${{ inputs.version }}

  publish:
    name: Build and Publish
    if: needs.changelog.outputs.skipped == 'false'
    needs: changelog
    runs-on: ${{ inputs.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ needs.changelog.outputs.tag }}

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Setup repository
      uses: SwiftyLab/ci/actions/setup@main

    - name: Build package products and documentation
      run: |
        swift build -Xswiftc -emit-symbol-graph -Xswiftc -emit-extension-block-symbols -Xswiftc -emit-symbol-graph-dir -Xswiftc .build
        npm run build-doc
        npm run serve-doc
        npm run archive

    - name: Release GitHub Pages
      continue-on-error: true
      uses: JamesIves/github-pages-deploy-action@v4.6.1
      with:
          branch: gh-pages
          folder: .docc-build
          target-folder: docs
          clean: false
          commit-message: 'chore(GitHub Pages): release site for tag ${{ needs.changelog.outputs.tag }}'

    - name: Create GitHub Release
      continue-on-error: true
      uses: ncipollo/release-action@v1
      with:
        token: ${{ github.token }}
        tag: ${{ needs.changelog.outputs.tag }}
        body: ${{ needs.changelog.outputs.changelog }}
        artifacts: '*.zip'

    - name: Publish to CocoaPods trunk
      uses: actions/github-script@v6.1.0
      continue-on-error: true
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      with:
        script: |
          const exec = require('@actions/exec');
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          const pushArgs = [
            'trunk', 'push', '--skip-import-validation', '--skip-tests', '--allow-warnings', '--verbose'
          ];
          if (pkg.pods) {
            pkg.pods.forEach(async (pod) => {
              await  exec.exec('pod', [...pushArgs, '--synchronous', pod]);
            });
          } else {
            await exec.exec('pod', pushArgs);
          }

    - name: Publish to Swift Package Registry
      continue-on-error: true
      uses: twodayslate/swift-package-registry@v0.0.2
