name: "Run CocoaPods Linting"

on:
  workflow_call:
    inputs:
      matrix:
        description: The strategy-matrix to use containing OS
        required: false
        type: string
        default: >
          {
            "include": [
              {
                "os": "macos-latest"
              }
            ]
          }
      tracked-files:
        description: The files on which changes tracked and based on change actions are run
        required: false
        type: string
        default: |
          Sources/**/*.swift
          Tests/**/*
          *.podspec

jobs:
  cocoapods:
    name: Run linting on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check should proceed running steps
      id: precondition
      uses: SwiftyLab/ci/.github/actions/condition@main
      with:
        files: ${{ inputs.tracked-files }}

    - name: Setup repository
      if: steps.precondition.outputs.proceed == 'true'
      uses: SwiftyLab/ci/.github/actions/setup@main

    - name: Run tests
      if: steps.precondition.outputs.proceed == 'true'
      run: npm run pod-lint
