name: Run Tests with Swift Package

on:
  workflow_call:
    inputs:
      matrix:
        description: The strategy-matrix to use containing OS and Swift version
        required: true
        type: string
      tracked-files:
        description: The files on which changes tracked and based on change actions are run
        required: false
        type: string
        default: |
          Sources/**/*.swift
          Tests/**/*
          Package*.swift
      codecov-swift:
        description: The swift version for codecov upload
        required: false
        type: string
        default: '5.7'
      codecov-os:
        description: The runner OS for codecov upload
        required: false
        type: string
        default: ubuntu-latest
    secrets:
      CODECOV_TOKEN:
        description: Codecov token to upload code coverage
        required: true

jobs:
  swift-package:
    name: Run tests on ${{ matrix.os }} with swift version ${{ matrix.swift }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check should proceed running steps
      id: precondition
      uses: SwiftyLab/ci/actions/condition@main
      with:
        files: ${{ inputs.tracked-files }}

    - name: Setup repository
      if: steps.precondition.outputs.proceed == 'true'
      uses: SwiftyLab/ci/actions/setup@main
      with:
        swift: ${{ matrix.swift }}
        xcode: ${{ matrix.xcode }}

    - name: Run tests
      if: steps.precondition.outputs.proceed == 'true'
      run: npm run test

    - name: Swift Coverage Report
      if: |
        steps.precondition.outputs.proceed == 'true' &&
        matrix.swift == inputs.codecov-swift &&
        matrix.os == inputs.codecov-os &&
        (github.event_name == 'push' || github.event_name == 'pull_request')
      uses: maxep/spm-lcov-action@0.3.1
      with:
        file-format: lcov
        output-file: ./coverage.lcov

    - name: Codecov upload
      if: |
        steps.precondition.outputs.proceed == 'true' &&
        matrix.swift == inputs.codecov-swift &&
        matrix.os == inputs.codecov-os &&
        (github.event_name == 'push' || github.event_name == 'pull_request')
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
