name: Run Xcode Build

on:
  workflow_call:
    inputs:
      os:
        description: MacOS runner to run Xcode build on
        required: false
        type: string
        default: macos-latest
      xcode:
        description: Xcode version to use
        required: false
        type: string
        default: latest-stable
      platforms:
        description: Space separated platforms list
        required: false
        type: string
        default: ''
      tracked-files:
        description: The files on which changes tracked and based on change actions are run
        required: false
        type: string
        default: |
          Sources/**/*.swift
          Tests/**/*
          *.xcodeproj/**/*

jobs:
  xcode-test:
    name: Build on ${{ inputs.os }} with xcode version ${{ inputs.xcode }}
    runs-on: ${{ inputs.os }}

    steps:
    - name: Check should proceed running steps
      id: precondition
      uses: SwiftyLab/ci/actions/condition@swift-codeql
      with:
        files: ${{ inputs.tracked-files }}

    - name: Setup repository
      if: steps.precondition.outputs.proceed == 'true'
      uses: SwiftyLab/ci/actions/setup@swift-codeql
      with:
        xcode: ${{ inputs.xcode }}

    - name: Build with Xcode
      if: steps.precondition.outputs.proceed == 'true'
      run: npm run xcodebuild -- ${{ inputs.platforms }}
