name: Run Xcode Build

on:
  workflow_call:
    inputs:
      matrix:
        description: The strategy-matrix to use containing OS
        required: false
        type: string
        default: >
          {
            "include": [
              {
                "os": "macos-latest",
                "xcode": "latest-stable",
                "platform": "macOS"
              },
              {
                "os": "macos-latest",
                "xcode": "latest-stable",
                "platform": "watchOS"
              },
              {
                "os": "macos-latest",
                "xcode": "latest-stable",
                "platform": "tvOS"
              },
              {
                "os": "macos-latest",
                "xcode": "latest-stable",
                "platform": "iOS"
              },
              {
                "os": "macos-latest",
                "xcode": "latest-stable",
                "platform": "mac-catalyst"
              }
            ]
          }
      tracked-files:
        description: The files on which changes tracked and based on change actions are run
        required: false
        type: string
        default: |
          Sources/**/*.swift
          Tests/**/*
          *.xcodeproj/**/*

jobs:
  xcode-test:
    name: Build on ${{ matrix.os }} for platform ${{ matrix.platform }} and xcode version ${{ matrix.xcode }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check should proceed running steps
      id: precondition
      uses: SwiftyLab/ci/actions/condition@main
      with:
        files: ${{ inputs.tracked-files }}

    - name: Setup repository
      if: steps.precondition.outputs.proceed == 'true'
      uses: SwiftyLab/ci/actions/setup@main
      with:
        xcode: ${{ matrix.xcode }}

    - name: Build with Xcode
      if: steps.precondition.outputs.proceed == 'true'
      run: npm run xcodebuild -- --platform $PLATFORM
      env:
        PLATFORM: ${{ matrix.platform }}
